// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MipymeAsistencia.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MipymeAsistencia.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260801162459_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.ConfiguracionSede", b =>
                {
                    b.Property<int>("IdSede")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_sede");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSede"));

                    b.Property<int>("DuracionAlmuerzoMinutos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(60)
                        .HasColumnName("duracion_almuerzo_minutos");

                    b.Property<TimeSpan>("HoraEntradaOficial")
                        .HasColumnType("interval")
                        .HasColumnName("hora_entrada_oficial");

                    b.Property<TimeSpan>("HoraSalidaOficial")
                        .HasColumnType("interval")
                        .HasColumnName("hora_salida_oficial");

                    b.Property<decimal>("LatitudSede")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitud_sede");

                    b.Property<decimal>("LongitudSede")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitud_sede");

                    b.Property<string>("NombreSede")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Sede Principal")
                        .HasColumnName("nombre_sede");

                    b.Property<DateTime?>("QrUltimaActualizacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("qr_ultima_actualizacion");

                    b.Property<int>("RadioToleranciaMetros")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(100)
                        .HasColumnName("radio_tolerancia_metros");

                    b.Property<string>("TokenQrActual")
                        .HasColumnType("text")
                        .HasColumnName("token_qr_actual");

                    b.HasKey("IdSede");

                    b.ToTable("configuracion_sede", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Empleado", b =>
                {
                    b.Property<int>("IdEmpleado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEmpleado"));

                    b.Property<string>("Apellidos")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("apellidos");

                    b.Property<string>("CargoFuncion")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("cargo_funcion");

                    b.Property<string>("CedulaIdentificacion")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("cedula_identificacion");

                    b.Property<decimal>("DiasVacacionesAcumuladas")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("dias_vacaciones_acumuladas");

                    b.Property<DateTime>("FechaContratacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_contratacion");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("foto_url");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    b.Property<string>("Nombres")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("nombres");

                    b.Property<string>("Responsabilidades")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("responsabilidades");

                    b.Property<decimal>("SalarioBaseMensual")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salario_base_mensual");

                    b.HasKey("IdEmpleado");

                    b.HasIndex("CedulaIdentificacion")
                        .IsUnique();

                    b.HasIndex("IdUsuario")
                        .IsUnique();

                    b.ToTable("empleados", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.EvaluacionDesempeno", b =>
                {
                    b.Property<int>("IdEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_evaluacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEvaluacion"));

                    b.Property<int?>("CalificacionCumplimientoFunciones")
                        .HasColumnType("integer")
                        .HasColumnName("calificacion_cumplimiento_funciones");

                    b.Property<DateTime?>("FechaEvaluacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_evaluacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IdEvaluador")
                        .HasColumnType("integer")
                        .HasColumnName("id_evaluador");

                    b.Property<string>("Observaciones")
                        .HasColumnType("text")
                        .HasColumnName("observaciones");

                    b.Property<string>("Periodo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("periodo");

                    b.Property<decimal?>("PorcentajePuntualidad")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasColumnName("porcentaje_puntualidad");

                    b.HasKey("IdEvaluacion");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdEvaluador");

                    b.ToTable("evaluaciones_desempeno", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HistorialAsistencia", b =>
                {
                    b.Property<int>("IdAsistencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_asistencia");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdAsistencia"));

                    b.Property<decimal>("DistanciaCalculadaMetros")
                        .HasPrecision(8, 2)
                        .HasColumnType("numeric(8,2)")
                        .HasColumnName("distancia_calculada_metros");

                    b.Property<bool>("EstaDentroDelRangoGps")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("esta_dentro_del_rango_gps");

                    b.Property<string>("EstadoAsistencia")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("estado_asistencia");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<TimeSpan?>("FinAlmuerzo")
                        .HasColumnType("interval")
                        .HasColumnName("fin_almuerzo");

                    b.Property<TimeSpan>("HoraEntrada")
                        .HasColumnType("interval")
                        .HasColumnName("hora_entrada");

                    b.Property<TimeSpan?>("HoraSalida")
                        .HasColumnType("interval")
                        .HasColumnName("hora_salida");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<TimeSpan?>("InicioAlmuerzo")
                        .HasColumnType("interval")
                        .HasColumnName("inicio_almuerzo");

                    b.Property<decimal>("LatitudMarcaje")
                        .HasPrecision(10, 8)
                        .HasColumnType("numeric(10,8)")
                        .HasColumnName("latitud_marcaje");

                    b.Property<decimal>("LongitudMarcaje")
                        .HasPrecision(11, 8)
                        .HasColumnType("numeric(11,8)")
                        .HasColumnName("longitud_marcaje");

                    b.Property<int>("MinutosTardanza")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("minutos_tardanza");

                    b.HasKey("IdAsistencia");

                    b.HasIndex("EstadoAsistencia");

                    b.HasIndex("IdEmpleado", "Fecha");

                    b.ToTable("historial_asistencia", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HistorialPermisoVacacion", b =>
                {
                    b.Property<int>("IdSolicitud")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_solicitud");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdSolicitud"));

                    b.Property<decimal>("DiasSolicitados")
                        .HasPrecision(4, 1)
                        .HasColumnType("numeric(4,1)")
                        .HasColumnName("dias_solicitados");

                    b.Property<string>("EstadoSolicitud")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Pendiente")
                        .HasColumnName("estado_solicitud");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_fin");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_inicio");

                    b.Property<DateTime?>("FechaRespuesta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_respuesta");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<int?>("IdUsuarioAprobador")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_aprobador");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.Property<string>("TipoSolicitud")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("tipo_solicitud");

                    b.HasKey("IdSolicitud");

                    b.HasIndex("IdUsuarioAprobador");

                    b.HasIndex("IdEmpleado", "FechaInicio");

                    b.ToTable("historial_permisos_vacaciones", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HistorialPlanilla", b =>
                {
                    b.Property<int>("IdPlanilla")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_planilla");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPlanilla"));

                    b.Property<decimal>("AcumuladoAguinaldo")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("acumulado_aguinaldo");

                    b.Property<DateTime>("FechaEmision")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_emision");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<decimal>("InssLaboral")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("inss_laboral");

                    b.Property<decimal>("IrLaboral")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("ir_laboral");

                    b.Property<decimal>("OtrasDeducciones")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("otras_deducciones");

                    b.Property<decimal>("PagoHorasExtras")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("pago_horas_extras");

                    b.Property<string>("PeriodoMesAnio")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("periodo_mes_anio");

                    b.Property<decimal>("SalarioBase")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salario_base");

                    b.Property<decimal>("SalarioBruto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salario_bruto");

                    b.Property<decimal>("SalarioNeto")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salario_neto");

                    b.Property<decimal>("TotalDeducciones")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_deducciones");

                    b.Property<decimal>("TotalHorasExtras")
                        .ValueGeneratedOnAdd()
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)")
                        .HasDefaultValue(0m)
                        .HasColumnName("total_horas_extras");

                    b.HasKey("IdPlanilla");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("PeriodoMesAnio");

                    b.ToTable("historial_planillas", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HoraExtra", b =>
                {
                    b.Property<int>("IdHoraExtra")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_hora_extra");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdHoraExtra"));

                    b.Property<decimal>("CantidadHoras")
                        .HasPrecision(4, 2)
                        .HasColumnType("numeric(4,2)")
                        .HasColumnName("cantidad_horas");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Aprobado")
                        .HasColumnName("estado");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<int?>("IdUsuarioAprobador")
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario_aprobador");

                    b.Property<decimal>("MontoPagar")
                        .HasPrecision(12, 2)
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("monto_pagar");

                    b.Property<string>("Motivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("motivo");

                    b.HasKey("IdHoraExtra");

                    b.HasIndex("IdEmpleado");

                    b.HasIndex("IdUsuarioAprobador");

                    b.ToTable("horas_extras", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("descripcion");

                    b.Property<string>("NombreRol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("nombre_rol");

                    b.HasKey("IdRol");

                    b.HasIndex("NombreRol")
                        .IsUnique();

                    b.ToTable("roles", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_usuario");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("Es2FaActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("es_2fa_activo");

                    b.Property<bool>("EstadoActivo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("estado_activo");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer")
                        .HasColumnName("id_rol");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Secret2Fa")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("secret_2fa");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("IdRol");

                    b.ToTable("usuarios", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.ValidacionQrMarcaje", b =>
                {
                    b.Property<int>("IdValidacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id_validacion");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdValidacion"));

                    b.Property<string>("CodigoOtpGenerado")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("character varying(6)")
                        .HasColumnName("codigo_otp_generado");

                    b.Property<DateTime>("FechaCreacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_creacion")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_expiracion");

                    b.Property<bool>("FueUtilizado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("fue_utilizado");

                    b.Property<int>("IdEmpleado")
                        .HasColumnType("integer")
                        .HasColumnName("id_empleado");

                    b.Property<int>("IntentosFallidos")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("intentos_fallidos");

                    b.Property<string>("TokenQrEscaneado")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("token_qr_escaneado");

                    b.HasKey("IdValidacion");

                    b.HasIndex("IdEmpleado");

                    b.ToTable("validaciones_qr_marcaje", (string)null);
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Empleado", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Usuario", "Usuario")
                        .WithOne("Empleado")
                        .HasForeignKey("MipymeAsistencia.Domain.Entities.Empleado", "IdUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.EvaluacionDesempeno", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Evaluaciones")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MipymeAsistencia.Domain.Entities.Usuario", "Evaluador")
                        .WithMany("EvaluacionesRealizadas")
                        .HasForeignKey("IdEvaluador")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Empleado");

                    b.Navigation("Evaluador");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HistorialAsistencia", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Empleado", "Empleado")
                        .WithMany("HistorialAsistencias")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HistorialPermisoVacacion", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Solicitudes")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MipymeAsistencia.Domain.Entities.Usuario", "UsuarioAprobador")
                        .WithMany("PermisosAprobados")
                        .HasForeignKey("IdUsuarioAprobador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");

                    b.Navigation("UsuarioAprobador");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HistorialPlanilla", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Empleado", "Empleado")
                        .WithMany("Planillas")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.HoraExtra", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Empleado", "Empleado")
                        .WithMany("HorasExtras")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MipymeAsistencia.Domain.Entities.Usuario", "UsuarioAprobador")
                        .WithMany("HorasExtrasAprobadas")
                        .HasForeignKey("IdUsuarioAprobador")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empleado");

                    b.Navigation("UsuarioAprobador");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Rol", "Rol")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.ValidacionQrMarcaje", b =>
                {
                    b.HasOne("MipymeAsistencia.Domain.Entities.Empleado", "Empleado")
                        .WithMany("ValidacionesQrMarcaje")
                        .HasForeignKey("IdEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Empleado", b =>
                {
                    b.Navigation("Evaluaciones");

                    b.Navigation("HistorialAsistencias");

                    b.Navigation("HorasExtras");

                    b.Navigation("Planillas");

                    b.Navigation("Solicitudes");

                    b.Navigation("ValidacionesQrMarcaje");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Rol", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("MipymeAsistencia.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Empleado");

                    b.Navigation("EvaluacionesRealizadas");

                    b.Navigation("HorasExtrasAprobadas");

                    b.Navigation("PermisosAprobados");
                });
#pragma warning restore 612, 618
        }
    }
}
