using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MipymeAsistencia.Infrastructure.Persistence.Migrations
{
    /// <inheritdoc />
    public partial class AddDepartamentoToEmpleadoAndPlanillaPorDepartamento : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.Sql("ALTER TABLE empleados ADD COLUMN IF NOT EXISTS departamento character varying(100) NOT NULL DEFAULT 'General';");

            migrationBuilder.Sql(@"CREATE TABLE IF NOT EXISTS auditoria_logs (
                id_log integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                entidad character varying(50) NOT NULL,
                id_registro integer NOT NULL,
                accion character varying(50) NOT NULL,
                usuario character varying(100) NOT NULL,
                descripcion text NOT NULL,
                detalles_json jsonb,
                fecha_evento timestamp with time zone NOT NULL DEFAULT (NOW())
            );");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "auditoria_logs");

            migrationBuilder.DropColumn(
                name: "departamento",
                table: "empleados");
        }
    }
}
